language: php

php:
  # - 7.1 # Version 7.1.33 | End of Life: 1 Dec 2019
  # - 7.2 # Version 7.2.30 | End of Life: 30 Nov 2020
  - 7.3 # End of Life: 6 Dec 2021
  #- 7.4 # End of Life: 28 Nov 2022
  #- 8.0 # End of Life: 26 Nov 2023
  #- nightly

env:
  global:
    - XDEBUG_MODE=coverage
    - DOCKER_COMPOSE_VERSION=1.27.4
    #- WOMBAT_HOST=172.77.62.74 # Value from docker-compose.yml
    - TESTBENCH=5.*

  # Used with matrix for older testbench/Laravel versions
  #- TESTBENCH=3.7.*
  #- TESTBENCH=3.8.*
  #- TESTBENCH=3.*
  #- TESTBENCH=4.*
  #- TESTBENCH=dev-master

services:
  - docker

# blocklist
branches:
  except:
  - /^analysis-.*$/ # Ignore StyleCI PR's

before_install:
  # Update docker-compose version
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

  # Fix used when working with older versions of testbench/Laravel 
  #- composer require --dev "phpunit/phpunit:8.*" --prefer-dist --no-update
  #- composer require --dev "orchestra/testbench:${TESTBENCH}" --prefer-dist --no-update

install:
  # Build WombatDialer for Integration Testing
  - docker-compose -f test/builds/wbt/docker-compose.yml up -d --force-recreate --build
  - sleep 10 # Allow WombatDialer time to start
  
jobs:
  allow_failures:
  - php: 8.0
  - php: nightly

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction
  
script:
  #- mkdir -p build/logs
  #- export XDEBUG_MODE=debug
  #- phpunit --verbose --coverage-clover build/logs/clover.xml
  - vendor/bin/phpunit --verbose
  # - phpunit --verbose --coverage-text

after_script:
#after_success:
  - travis_retry php vendor/bin/php-coveralls -v

# configure notifications (email, IRC, campfire etc)
notifications:
  irc: "irc.freenode.org#poing"
